
#Ambiente de desenvolvimento do PostgreSQL

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sgl}
spring.datasource.username=${DB_USER:}
spring.datasource.password=${DB_PASSWD:}

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true