CREATE TABLE residuos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    laboratorio_id BIGINT NOT NULL,
    gerador_id BIGINT NOT NULL,
    projeto_id BIGINT,
    gestor_responsavel_id BIGINT,

    descricao VARCHAR(1000) NOT NULL,
    processo_origem VARCHAR(1000) NOT NULL,
    recipiente VARCHAR(255) NOT NULL,
    quantidade NUMERIC(12,3) NOT NULL,
    unidade_medida VARCHAR(255) NOT NULL,

    nivel_risco_informado VARCHAR(255) NOT NULL,
    nivel_risco_confirmado VARCHAR(255),

    observacao_gerador VARCHAR(1000),
    observacao_gestor VARCHAR(1000),
    local_armazenamento_temporario VARCHAR(255),
    destino_final_previsto VARCHAR(500),
    destino_final_confirmado VARCHAR(500),

    codigo_rastreio VARCHAR(80),
    qr_code_conteudo VARCHAR(500),
    status VARCHAR(255) NOT NULL,

    data_informacao TIMESTAMP NOT NULL,
    data_recebimento TIMESTAMP,
    data_liberacao TIMESTAMP,
    data_armazenamento_temporario TIMESTAMP,
    data_prevista_despacho DATE,
    data_despacho TIMESTAMP,

    CONSTRAINT uk_residuos_public_id UNIQUE (public_id),
    CONSTRAINT uk_residuos_codigo_rastreio UNIQUE (codigo_rastreio),
    CONSTRAINT ck_residuos_quantidade_positiva CHECK (quantidade > 0),

    CONSTRAINT fk_residuo_laboratorio
        FOREIGN KEY (laboratorio_id) REFERENCES laboratorios(id),
    CONSTRAINT fk_residuo_gerador
        FOREIGN KEY (gerador_id) REFERENCES usuarios(id),
    CONSTRAINT fk_residuo_projeto
        FOREIGN KEY (projeto_id) REFERENCES projetos(id),
    CONSTRAINT fk_residuo_gestor
        FOREIGN KEY (gestor_responsavel_id) REFERENCES usuarios(id)
);

CREATE TABLE componentes_residuo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    residuo_id BIGINT NOT NULL,
    produto_id BIGINT,
    nome_componente VARCHAR(255) NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    concentracao_ou_quantidade VARCHAR(100),
    observacao VARCHAR(500),

    CONSTRAINT uk_componentes_residuo_public_id UNIQUE (public_id),
    CONSTRAINT fk_componente_residuo
        FOREIGN KEY (residuo_id) REFERENCES residuos(id) ON DELETE CASCADE,
    CONSTRAINT fk_componente_produto
        FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE SET NULL
);

CREATE TABLE residuo_riscos_informados (
    residuo_id BIGINT NOT NULL,
    risco VARCHAR(255) NOT NULL,

    CONSTRAINT pk_residuo_riscos_informados PRIMARY KEY (residuo_id, risco),
    CONSTRAINT fk_residuo_riscos_informados
        FOREIGN KEY (residuo_id) REFERENCES residuos(id) ON DELETE CASCADE
);

CREATE TABLE residuo_riscos_confirmados (
    residuo_id BIGINT NOT NULL,
    risco VARCHAR(255) NOT NULL,

    CONSTRAINT pk_residuo_riscos_confirmados PRIMARY KEY (residuo_id, risco),
    CONSTRAINT fk_residuo_riscos_confirmados
        FOREIGN KEY (residuo_id) REFERENCES residuos(id) ON DELETE CASCADE
);

CREATE TABLE historico_residuo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    residuo_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    acao VARCHAR(120) NOT NULL,
    observacao VARCHAR(1000),
    data_hora TIMESTAMP NOT NULL,

    CONSTRAINT uk_historico_residuo_public_id UNIQUE (public_id),
    CONSTRAINT fk_historico_residuo
        FOREIGN KEY (residuo_id) REFERENCES residuos(id) ON DELETE CASCADE,
    CONSTRAINT fk_historico_residuo_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_residuos_status ON residuos(status);
CREATE INDEX idx_residuos_laboratorio ON residuos(laboratorio_id);
CREATE INDEX idx_residuos_data_informacao ON residuos(data_informacao);
CREATE INDEX idx_historico_residuo_data ON historico_residuo(residuo_id, data_hora);
