CREATE TABLE classes_residuo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    unidade_id BIGINT NOT NULL,

    codigo VARCHAR(30) NOT NULL,
    descricao VARCHAR(500) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_classes_residuo_public_id
        UNIQUE (public_id),

    CONSTRAINT uk_classes_residuo_unidade_codigo
        UNIQUE (unidade_id, codigo),

    CONSTRAINT fk_classe_residuo_unidade
        FOREIGN KEY (unidade_id)
        REFERENCES unidades(id)
);


CREATE TABLE residuo_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    residuo_id BIGINT NOT NULL,
    classe_residuo_id BIGINT NOT NULL,

    etapa VARCHAR(30) NOT NULL,

    codigo_snapshot VARCHAR(30) NOT NULL,
    descricao_snapshot VARCHAR(500) NOT NULL,

    CONSTRAINT fk_residuo_classe_residuo
        FOREIGN KEY (residuo_id)
        REFERENCES residuos(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_residuo_classe_catalogo
        FOREIGN KEY (classe_residuo_id)
        REFERENCES classes_residuo(id),

    CONSTRAINT uk_residuo_classe_etapa
        UNIQUE (residuo_id, classe_residuo_id, etapa),

    CONSTRAINT ck_residuo_classe_etapa
        CHECK (etapa IN ('INFORMADA', 'CONFIRMADA'))
);


CREATE INDEX idx_classes_residuo_unidade
    ON classes_residuo(unidade_id);

CREATE INDEX idx_residuo_classes_residuo
    ON residuo_classes(residuo_id);
    
INSERT INTO classes_residuo (
    unidade_id,
    codigo,
    descricao,
    ativo
)

SELECT
    id,
    'A',
    'Solventes ou soluções de substâncias orgânicas que não contenham halogênios',
    TRUE
FROM unidades
ON CONFLICT (unidade_id, codigo) DO NOTHING;


INSERT INTO classes_residuo (
    unidade_id,
    codigo,
    descricao,
    ativo
)
SELECT
    id,
    'B',
    'Solventes ou soluções orgânicas que contenham halogênios',
    TRUE
FROM unidades
ON CONFLICT (unidade_id, codigo) DO NOTHING;


INSERT INTO classes_residuo (
    unidade_id,
    codigo,
    descricao,
    ativo
)
SELECT
    id,
    'F',
    'Resíduos sólidos de produtos químicos orgânicos',
    TRUE
FROM unidades
ON CONFLICT (unidade_id, codigo) DO NOTHING;


INSERT INTO classes_residuo (
    unidade_id,
    codigo,
    descricao,
    ativo
)
SELECT
    id,
    'H',
    'Outros',
    TRUE
FROM unidades
ON CONFLICT (unidade_id, codigo) DO NOTHING;