CREATE TABLE locais_armazenamento_residuo(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

	public_id UUID NOT NULL DEFAULT gen_random_uuid(),
	
	unidade_id BIGINT NOT NULL,
	
	nome VARCHAR(150) NOT NULL,
	
	ativo BOOLEAN NOT NULL DEFAULT TRUE,
	
	CONSTRAINT uk_locais_armazenamento_residuo_public_id
		UNIQUE (public_id),
		
	CONSTRAINT uk_locais_armazenamento_residuo_unidade_nome
		UNIQUE (unidade_id, nome),
		
	CONSTRAINT fk_local_armazenamento_residuo_unidade
		FOREIGN KEY (unidade_id)
		REFERENCES unidades(id)
);


CREATE INDEX idx_locais_armazenamento_residuo_unidade
	ON locais_armazenamento_residuo(unidade_id);
	
ALTER TABLE residuos
	ADD COLUMN local_armazenamento_residuo_id BIGINT;
	
ALTER TABLE residuos
	ADD COLUMN complemento_local_armazenamento VARCHAR(150);
	
ALTER TABLE residuos
	ADD CONSTRAINT fk_residuo_local_armazenamento
		FOREIGN KEY (local_armazenamento_residuo_id)
		REFERENCES locais_armazenamento_residuo(id);