CREATE TABLE modelos_residuo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    unidade_id BIGINT NOT NULL,

    nome VARCHAR(150) NOT NULL,

    descricao VARCHAR(1000) NOT NULL,

    processo_origem VARCHAR(1000) NOT NULL,

    estado_fisico VARCHAR(255) NOT NULL,

    tratamento_realizado BOOLEAN NOT NULL,

    descricao_tratamento VARCHAR(1000),

    recipiente VARCHAR(255) NOT NULL,

    unidade_medida VARCHAR(255) NOT NULL,

    nivel_risco VARCHAR(255) NOT NULL,

    observacao_seguranca VARCHAR(1000),

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_modelos_residuo_public_id
        UNIQUE (public_id),

    CONSTRAINT uk_modelos_residuo_unidade_nome
        UNIQUE (unidade_id, nome),

    CONSTRAINT fk_modelo_residuo_unidade
        FOREIGN KEY (unidade_id)
        REFERENCES unidades(id)
);


CREATE TABLE modelo_residuo_riscos (
    modelo_residuo_id BIGINT NOT NULL,

    risco VARCHAR(255) NOT NULL,

    CONSTRAINT pk_modelo_residuo_riscos
        PRIMARY KEY (modelo_residuo_id, risco),

    CONSTRAINT fk_modelo_residuo_riscos
        FOREIGN KEY (modelo_residuo_id)
        REFERENCES modelos_residuo(id)
        ON DELETE CASCADE
);


CREATE TABLE modelo_residuo_medidas_seguranca (
    modelo_residuo_id BIGINT NOT NULL,

    medida VARCHAR(100) NOT NULL,

    CONSTRAINT pk_modelo_residuo_medidas_seguranca
        PRIMARY KEY (modelo_residuo_id, medida),

    CONSTRAINT fk_modelo_residuo_medidas_seguranca
        FOREIGN KEY (modelo_residuo_id)
        REFERENCES modelos_residuo(id)
        ON DELETE CASCADE
);


CREATE TABLE modelo_residuo_classes (
    modelo_residuo_id BIGINT NOT NULL,

    classe_residuo_id BIGINT NOT NULL,

    CONSTRAINT pk_modelo_residuo_classes
        PRIMARY KEY (
            modelo_residuo_id,
            classe_residuo_id
        ),

    CONSTRAINT fk_modelo_residuo_classes_modelo
        FOREIGN KEY (modelo_residuo_id)
        REFERENCES modelos_residuo(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_modelo_residuo_classes_classe
        FOREIGN KEY (classe_residuo_id)
        REFERENCES classes_residuo(id)
);


CREATE TABLE componentes_modelo_residuo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    modelo_residuo_id BIGINT NOT NULL,

    produto_id BIGINT,

    nome_componente VARCHAR(255) NOT NULL,

    principal BOOLEAN NOT NULL DEFAULT FALSE,

    concentracao_ou_quantidade VARCHAR(100),

    observacao VARCHAR(500),

    CONSTRAINT uk_componentes_modelo_residuo_public_id
        UNIQUE (public_id),

    CONSTRAINT fk_componente_modelo_residuo
        FOREIGN KEY (modelo_residuo_id)
        REFERENCES modelos_residuo(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_componente_modelo_produto
        FOREIGN KEY (produto_id)
        REFERENCES produtos(id)
        ON DELETE SET NULL
);


CREATE INDEX idx_modelos_residuo_unidade
    ON modelos_residuo(unidade_id);


CREATE INDEX idx_componentes_modelo_residuo_modelo
    ON componentes_modelo_residuo(modelo_residuo_id);