CREATE TABLE scis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    public_id UUID NOT NULL,

    projeto_id BIGINT NOT NULL,

    codigo_seg VARCHAR(18) NOT NULL,

    nome VARCHAR(255) NOT NULL,

    responsavel VARCHAR(255),

    data_inicio DATE NOT NULL,
    data_fim DATE,

    status VARCHAR(64) NOT NULL DEFAULT 'ATIVO',

    situacao_execucao VARCHAR(64) NOT NULL DEFAULT 'NAO_INFORMADO',

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_scis_public_id
        UNIQUE (public_id),

    CONSTRAINT fk_sci_projeto
        FOREIGN KEY (projeto_id)
        REFERENCES projetos(id),

    CONSTRAINT ck_scis_codigo_seg_nao_vazio
        CHECK (TRIM(codigo_seg) <> ''),

    CONSTRAINT ck_scis_periodo
        CHECK (
            data_fim IS NULL
            OR data_fim >= data_inicio
        ),

    CONSTRAINT ck_scis_status
        CHECK (
            status IN (
                'ATIVO',
                'ENCERRADO_COM_AVALIACAO_PENDENTE',
                'CONCLUIDO'
            )
        ),

    CONSTRAINT ck_scis_situacao_execucao
        CHECK (
            situacao_execucao IN (
                'NAO_INFORMADO',
                'EM_ANDAMENTO_NO_PRAZO',
                'EM_ANDAMENTO_ATRASADO',
                'EXECUCAO_CANCELADA'
            )
        )
);

CREATE INDEX idx_scis_projeto_id
    ON scis(projeto_id);

CREATE INDEX idx_scis_codigo_seg
    ON scis(codigo_seg);