CREATE TABLE atividades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    sci_id BIGINT NOT NULL,

    codigo_seg VARCHAR(22) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    responsavel VARCHAR(255),

    data_inicio DATE NOT NULL,
    data_fim DATE,

    status VARCHAR(64) NOT NULL DEFAULT 'ATIVO',
    situacao_execucao VARCHAR(64) NOT NULL DEFAULT 'NAO_INFORMADO',

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_atividades_public_id
        UNIQUE (public_id),

    CONSTRAINT fk_atividade_sci
        FOREIGN KEY (sci_id)
        REFERENCES scis(id),

    CONSTRAINT ck_atividades_codigo_seg_nao_vazio
        CHECK (TRIM(codigo_seg) <> ''),

    CONSTRAINT ck_atividades_periodo
        CHECK (
            data_fim IS NULL
            OR data_fim >= data_inicio
        ),

    CONSTRAINT ck_atividades_status
        CHECK (
            status IN (
                'ATIVO',
                'ENCERRADO_COM_AVALIACAO_PENDENTE',
                'CONCLUIDO'
            )
        ),

    CONSTRAINT ck_atividades_situacao_execucao
        CHECK (
            situacao_execucao IN (
                'NAO_INFORMADO',
                'EM_ANDAMENTO_NO_PRAZO',
                'EM_ANDAMENTO_ATRASADO',
                'EXECUCAO_CANCELADA'
            )
        )
);

CREATE INDEX idx_atividades_sci_id
    ON atividades(sci_id);

CREATE INDEX idx_atividades_codigo_seg
    ON atividades(codigo_seg);