CREATE TABLE historico_prorrogacao_projeto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,

    projeto_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,

    data_fim_anterior DATE NOT NULL,
    data_fim_nova DATE NOT NULL,

    justificativa VARCHAR(1000) NOT NULL,
    data_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_hist_prorrogacao_projeto_public_id
        UNIQUE (public_id),

    CONSTRAINT fk_hist_prorrogacao_projeto_projeto
        FOREIGN KEY (projeto_id)
        REFERENCES projetos(id),

    CONSTRAINT fk_hist_prorrogacao_projeto_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id),

    CONSTRAINT ck_hist_prorrogacao_projeto_justificativa
        CHECK (TRIM(justificativa) <> ''),

    CONSTRAINT ck_hist_prorrogacao_projeto_periodo
        CHECK (data_fim_nova > data_fim_anterior)
);

CREATE INDEX idx_hist_prorrogacao_projeto_projeto
    ON historico_prorrogacao_projeto(projeto_id);

CREATE INDEX idx_hist_prorrogacao_projeto_data_hora
    ON historico_prorrogacao_projeto(data_hora);


CREATE TABLE historico_prorrogacao_sci (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,

    sci_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,

    data_fim_anterior DATE NOT NULL,
    data_fim_nova DATE NOT NULL,

    justificativa VARCHAR(1000) NOT NULL,
    data_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_hist_prorrogacao_sci_public_id
        UNIQUE (public_id),

    CONSTRAINT fk_hist_prorrogacao_sci_sci
        FOREIGN KEY (sci_id)
        REFERENCES scis(id),

    CONSTRAINT fk_hist_prorrogacao_sci_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id),

    CONSTRAINT ck_hist_prorrogacao_sci_justificativa
        CHECK (TRIM(justificativa) <> ''),

    CONSTRAINT ck_hist_prorrogacao_sci_periodo
        CHECK (data_fim_nova > data_fim_anterior)
);

CREATE INDEX idx_hist_prorrogacao_sci_sci
    ON historico_prorrogacao_sci(sci_id);

CREATE INDEX idx_hist_prorrogacao_sci_data_hora
    ON historico_prorrogacao_sci(data_hora);


CREATE TABLE historico_prorrogacao_atividade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,

    atividade_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,

    data_fim_anterior DATE NOT NULL,
    data_fim_nova DATE NOT NULL,

    justificativa VARCHAR(1000) NOT NULL,
    data_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_hist_prorrogacao_atividade_public_id
        UNIQUE (public_id),

    CONSTRAINT fk_hist_prorrogacao_atividade_atividade
        FOREIGN KEY (atividade_id)
        REFERENCES atividades(id),

    CONSTRAINT fk_hist_prorrogacao_atividade_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id),

    CONSTRAINT ck_hist_prorrogacao_atividade_justificativa
        CHECK (TRIM(justificativa) <> ''),

    CONSTRAINT ck_hist_prorrogacao_atividade_periodo
        CHECK (data_fim_nova > data_fim_anterior)
);

CREATE INDEX idx_hist_prorrogacao_atividade_atividade
    ON historico_prorrogacao_atividade(atividade_id);

CREATE INDEX idx_hist_prorrogacao_atividade_data_hora
    ON historico_prorrogacao_atividade(data_hora);