CREATE TABLE vinculos_estagio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    estagiario_id BIGINT NOT NULL,
    orientador_id BIGINT,

    data_inicio DATE NOT NULL,
    data_fim_prevista DATE,
    data_fim_efetiva DATE,

    tipo_bolsa VARCHAR(255) NOT NULL,
    situacao VARCHAR(30) NOT NULL,

    observacao VARCHAR(255),

    CONSTRAINT uk_vinculos_estagio_public_id
        UNIQUE (public_id),

    CONSTRAINT fk_vinculos_estagio_estagiario
        FOREIGN KEY (estagiario_id)
        REFERENCES estagiarios(id),

    CONSTRAINT fk_vinculos_estagio_orientador
        FOREIGN KEY (orientador_id)
        REFERENCES usuarios(id),

    CONSTRAINT ck_vinculos_estagio_fim_previsto
        CHECK (
            data_fim_prevista IS NULL
            OR data_fim_prevista >= data_inicio
        ),

    CONSTRAINT ck_vinculos_estagio_fim_efetivo
        CHECK (
            data_fim_efetiva IS NULL
            OR data_fim_efetiva >= data_inicio
        )
);

CREATE INDEX idx_vinculos_estagio_estagiario
    ON vinculos_estagio(estagiario_id);

CREATE INDEX idx_vinculos_estagio_orientador
    ON vinculos_estagio(orientador_id);

CREATE INDEX idx_vinculos_estagio_situacao
    ON vinculos_estagio(situacao);
    
    INSERT INTO vinculos_estagio (
    estagiario_id,
    orientador_id,
    data_inicio,
    data_fim_prevista,
    data_fim_efetiva,
    tipo_bolsa,
    situacao,
  	observacao
)
SELECT
    e.id,
    e.orientador_id,
    e.data_inicio_estagio,
    e.data_fim_estagio,

    CASE
        WHEN e.situacao_estagio = 'FINALIZADO'
            THEN e.data_fim_estagio
        ELSE NULL
    END,

    e.tipo_bolsa,
    e.situacao_estagio,
    e.observacao
FROM estagiarios e;