CREATE TABLE vinculo_estagio_atividade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    vinculo_estagio_id BIGINT NOT NULL,
    atividade_id BIGINT NOT NULL,

    data_inicio_participacao DATE NOT NULL,
    data_fim_participacao DATE,

    observacao VARCHAR(500),

    CONSTRAINT uk_vinculo_estagio_atividade_public_id
        UNIQUE (public_id),

    CONSTRAINT fk_vinculo_estagio_atividade_vinculo
        FOREIGN KEY (vinculo_estagio_id)
        REFERENCES vinculos_estagio(id),

    CONSTRAINT fk_vinculo_estagio_atividade_atividade
        FOREIGN KEY (atividade_id)
        REFERENCES atividades(id),

    CONSTRAINT ck_vinculo_estagio_atividade_periodo
        CHECK (
            data_fim_participacao IS NULL
            OR data_fim_participacao >= data_inicio_participacao
        )
);

CREATE INDEX idx_vinculo_estagio_atividade_vinculo
    ON vinculo_estagio_atividade(vinculo_estagio_id);

CREATE INDEX idx_vinculo_estagio_atividade_atividade
    ON vinculo_estagio_atividade(atividade_id);

CREATE INDEX idx_vinculo_estagio_atividade_vinculo_atividade
    ON vinculo_estagio_atividade(
        vinculo_estagio_id,
        atividade_id
    );