CREATE TABLE cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    unidade_id BIGINT NOT NULL,

    nome VARCHAR(150) NOT NULL,

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_cursos_public_id
        UNIQUE (public_id),

    CONSTRAINT uk_cursos_unidade_nome
        UNIQUE (unidade_id, nome),

    CONSTRAINT fk_cursos_unidade
        FOREIGN KEY (unidade_id)
        REFERENCES unidades(id)
);

CREATE INDEX idx_cursos_unidade
    ON cursos(unidade_id);

CREATE INDEX idx_cursos_ativo
    ON cursos(ativo);


ALTER TABLE vinculos_estagio
    ADD COLUMN formacao VARCHAR(40),
    ADD COLUMN formacao_outro VARCHAR(150),
    ADD COLUMN curso_id BIGINT,
    ADD COLUMN treinamento_seguranca_concluido
        BOOLEAN NOT NULL DEFAULT FALSE;


ALTER TABLE vinculos_estagio
    ADD CONSTRAINT fk_vinculos_estagio_curso
        FOREIGN KEY (curso_id)
        REFERENCES cursos(id);


CREATE INDEX idx_vinculos_estagio_curso
    ON vinculos_estagio(curso_id);