CREATE TABLE culturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    unidade_id BIGINT NOT NULL,

    nome VARCHAR(120) NOT NULL,

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_culturas_public_id
        UNIQUE (public_id),

    CONSTRAINT uk_culturas_unidade_nome
        UNIQUE (unidade_id, nome),

    CONSTRAINT fk_culturas_unidade
        FOREIGN KEY (unidade_id)
        REFERENCES unidades(id)
);

CREATE INDEX idx_culturas_unidade
    ON culturas(unidade_id);

CREATE INDEX idx_culturas_ativo
    ON culturas(ativo);


CREATE TABLE vinculo_estagio_atividade_cultura (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    vinculo_estagio_atividade_id BIGINT NOT NULL,

    cultura_id BIGINT NOT NULL,

    CONSTRAINT uk_vinculo_atividade_cultura_public_id
        UNIQUE (public_id),

    CONSTRAINT uk_vinculo_atividade_cultura
        UNIQUE (
            vinculo_estagio_atividade_id,
            cultura_id
        ),

    CONSTRAINT fk_vinculo_atividade_cultura_participacao
        FOREIGN KEY (vinculo_estagio_atividade_id)
        REFERENCES vinculo_estagio_atividade(id),

    CONSTRAINT fk_vinculo_atividade_cultura_cultura
        FOREIGN KEY (cultura_id)
        REFERENCES culturas(id)
);

CREATE INDEX idx_vinculo_atividade_cultura_participacao
    ON vinculo_estagio_atividade_cultura(
        vinculo_estagio_atividade_id
    );

CREATE INDEX idx_vinculo_atividade_cultura_cultura
    ON vinculo_estagio_atividade_cultura(
        cultura_id
    );