ALTER TABLE vinculos_estagio
    ADD COLUMN referencia_institucional VARCHAR(120);


CREATE TABLE historico_sincronizacao_vinculo_estagio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    vinculo_estagio_id BIGINT NOT NULL,

    tipo_evento VARCHAR(30) NOT NULL,
    origem VARCHAR(40) NOT NULL,

    referencia_evento VARCHAR(120),

    situacao_anterior VARCHAR(30),
    situacao_nova VARCHAR(30),

    data_fim_prevista_anterior DATE,
    data_fim_prevista_nova DATE,

    data_fim_efetiva_anterior DATE,
    data_fim_efetiva_nova DATE,

    data_hora_origem TIMESTAMP,
    data_hora_sincronizacao TIMESTAMP
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_hist_sync_vinculo_public_id
        UNIQUE (public_id),

    CONSTRAINT fk_hist_sync_vinculo
        FOREIGN KEY (vinculo_estagio_id)
        REFERENCES vinculos_estagio(id),

    CONSTRAINT uk_hist_sync_origem_evento
        UNIQUE (origem, referencia_evento)
);

CREATE INDEX idx_hist_sync_vinculo
    ON historico_sincronizacao_vinculo_estagio(
        vinculo_estagio_id
    );

CREATE INDEX idx_hist_sync_data
    ON historico_sincronizacao_vinculo_estagio(
        data_hora_sincronizacao
    );

CREATE INDEX idx_vinculo_referencia_institucional
    ON vinculos_estagio(
        referencia_institucional
    );