CREATE TABLE observacoes_vinculo_estagio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    vinculo_estagio_id BIGINT NOT NULL,
    tipo VARCHAR(40) NOT NULL,
    evento VARCHAR(50) NOT NULL,
    texto VARCHAR(1000),
    usuario_id BIGINT NOT NULL,
    data_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_observacao_vinculo_estagio_vinculo
        FOREIGN KEY (vinculo_estagio_id)
        REFERENCES vinculos_estagio (id),

    CONSTRAINT fk_observacao_vinculo_estagio_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id)
);

CREATE INDEX idx_observacao_vinculo_estagio_vinculo
    ON observacoes_vinculo_estagio (vinculo_estagio_id);

CREATE INDEX idx_observacao_vinculo_estagio_data_hora
    ON observacoes_vinculo_estagio (data_hora);
