-- ============================================================
-- V34 — Recipientes físicos individualizados do estoque
-- Etapa 7 — Unidade física / fracionamento
-- ============================================================

CREATE TABLE recipientes_estoque (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    public_id UUID NOT NULL,

    lote_id BIGINT NOT NULL,

    sequencial INTEGER NOT NULL,

    codigo_interno VARCHAR(180) NOT NULL,

    tipo_embalagem VARCHAR(30) NOT NULL,

    capacidade_inicial NUMERIC(19,6) NOT NULL,

    quantidade_disponivel NUMERIC(19,6) NOT NULL,

    unidade_medida VARCHAR(30) NOT NULL,

    estado VARCHAR(30) NOT NULL,

    data_abertura TIMESTAMP,

    data_esgotamento TIMESTAMP,

    observacao VARCHAR(500),

    CONSTRAINT fk_recipiente_lote
        FOREIGN KEY (lote_id)
        REFERENCES lote(id),

    CONSTRAINT uk_recipiente_public_id
        UNIQUE (public_id),

    CONSTRAINT uk_recipiente_codigo_interno
        UNIQUE (codigo_interno),

    CONSTRAINT uk_recipiente_lote_sequencial
        UNIQUE (lote_id, sequencial),

    CONSTRAINT ck_recipiente_sequencial_positivo
        CHECK (sequencial > 0),

    CONSTRAINT ck_recipiente_capacidade_positiva
        CHECK (capacidade_inicial > 0),

    CONSTRAINT ck_recipiente_quantidade_nao_negativa
        CHECK (quantidade_disponivel >= 0),

    CONSTRAINT ck_recipiente_quantidade_limite
        CHECK (
            quantidade_disponivel <= capacidade_inicial
        ),

    CONSTRAINT ck_recipiente_estado_fisico
        CHECK (

            (
                estado = 'FECHADO'
                AND quantidade_disponivel = capacidade_inicial
                AND data_abertura IS NULL
                AND data_esgotamento IS NULL
            )

            OR

            (
                estado = 'ABERTO'
                AND quantidade_disponivel > 0
                AND quantidade_disponivel <= capacidade_inicial
                AND data_abertura IS NOT NULL
                AND data_esgotamento IS NULL
            )

            OR

            (
                estado = 'ESGOTADO'
                AND quantidade_disponivel = 0
                AND data_esgotamento IS NOT NULL
            )
        )
);


CREATE INDEX idx_recipientes_estoque_lote
    ON recipientes_estoque (lote_id);


CREATE INDEX idx_recipientes_estoque_lote_estado
    ON recipientes_estoque (
        lote_id,
        estado
    );