-- ============================================================
-- V35 — Detalhes de movimentação por recipiente físico
-- Etapa 7 — Rastreabilidade individual do estoque
-- ============================================================

CREATE TABLE movimentacoes_recipiente (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    public_id UUID NOT NULL,

    movimentacao_estoque_id BIGINT NOT NULL,

    recipiente_estoque_id BIGINT NOT NULL,

    quantidade_anterior NUMERIC(19,6) NOT NULL,

    quantidade_movimentada NUMERIC(19,6) NOT NULL,

    quantidade_atual NUMERIC(19,6) NOT NULL,

    estado_anterior VARCHAR(30) NOT NULL,

    estado_atual VARCHAR(30) NOT NULL,

    abriu_recipiente BOOLEAN NOT NULL,

    esgotou_recipiente BOOLEAN NOT NULL,

    CONSTRAINT fk_mov_rec_movimentacao
        FOREIGN KEY (movimentacao_estoque_id)
        REFERENCES movimentacao_estoque(id),

    CONSTRAINT fk_mov_rec_recipiente
        FOREIGN KEY (recipiente_estoque_id)
        REFERENCES recipientes_estoque(id),

    CONSTRAINT uk_mov_rec_public_id
        UNIQUE (public_id),

    CONSTRAINT uk_mov_rec_movimentacao_recipiente
        UNIQUE (
            movimentacao_estoque_id,
            recipiente_estoque_id
        ),

    CONSTRAINT ck_mov_rec_quantidade_anterior
        CHECK (quantidade_anterior >= 0),

    CONSTRAINT ck_mov_rec_quantidade_movimentada
        CHECK (quantidade_movimentada > 0),

    CONSTRAINT ck_mov_rec_quantidade_atual
        CHECK (quantidade_atual >= 0),

    CONSTRAINT ck_mov_rec_estado_anterior
        CHECK (
            estado_anterior IN (
                'FECHADO',
                'ABERTO',
                'ESGOTADO'
            )
        ),

    CONSTRAINT ck_mov_rec_estado_atual
        CHECK (
            estado_atual IN (
                'FECHADO',
                'ABERTO',
                'ESGOTADO'
            )
        )
);


CREATE INDEX idx_mov_rec_movimentacao
    ON movimentacoes_recipiente (
        movimentacao_estoque_id
    );


CREATE INDEX idx_mov_rec_recipiente
    ON movimentacoes_recipiente (
        recipiente_estoque_id
    );