-- Etapa 7.3: modelos reutilizaveis, Pedido SOLUCAO e rastreabilidade.
-- Modelos sao catalogo de composicoes; a solicitacao real permanece em pedidos/itens_pedido.
CREATE TABLE modelos_solucao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    unidade_id BIGINT NOT NULL,
    nome VARCHAR(150) NOT NULL,
    descricao VARCHAR(1000),
    instrucoes_preparo VARCHAR(2000),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_modelo_solucao_public_id UNIQUE(public_id),
    CONSTRAINT uk_modelo_solucao_unidade_nome UNIQUE(unidade_id, nome),
    CONSTRAINT fk_modelo_solucao_unidade FOREIGN KEY(unidade_id) REFERENCES unidades(id)
);

CREATE INDEX idx_modelo_solucao_unidade ON modelos_solucao(unidade_id);

CREATE TABLE componentes_modelo_solucao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    modelo_solucao_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    ordem INTEGER NOT NULL,
    quantidade NUMERIC(19,6) NOT NULL,
    unidade_medida VARCHAR(30) NOT NULL,
    CONSTRAINT uk_componente_modelo_solucao_public_id UNIQUE(public_id),
    CONSTRAINT uk_componente_modelo_solucao_produto UNIQUE(modelo_solucao_id, produto_id),
    CONSTRAINT uk_componente_modelo_solucao_ordem UNIQUE(modelo_solucao_id, ordem),
    CONSTRAINT fk_componente_solucao_modelo FOREIGN KEY(modelo_solucao_id) REFERENCES modelos_solucao(id),
    CONSTRAINT fk_componente_solucao_produto FOREIGN KEY(produto_id) REFERENCES produtos(id),
    CONSTRAINT ck_componente_solucao_quantidade CHECK(quantidade > 0),
    CONSTRAINT ck_componente_solucao_ordem CHECK(ordem > 0)
);
CREATE INDEX idx_componente_solucao_modelo ON componentes_modelo_solucao(modelo_solucao_id);

ALTER TABLE pedidos ADD COLUMN tipo VARCHAR(20) NOT NULL DEFAULT 'PRODUTOS';
ALTER TABLE pedidos ADD COLUMN nome_solucao VARCHAR(150);
ALTER TABLE pedidos ADD COLUMN modelo_solucao_id BIGINT;
ALTER TABLE pedidos ADD COLUMN solucao_preparada_no_cancelamento BOOLEAN;
ALTER TABLE pedidos ADD COLUMN estoque_revertido_no_cancelamento BOOLEAN;
ALTER TABLE pedidos ADD CONSTRAINT fk_pedidos_modelo_solucao
    FOREIGN KEY(modelo_solucao_id) REFERENCES modelos_solucao(id);
CREATE INDEX idx_pedidos_tipo ON pedidos(tipo);

ALTER TABLE itens_pedido ADD COLUMN unidade_medida_solicitada VARCHAR(30);

