-- ============================================================
-- V37 — Domínio de Soluções
-- Etapa 7.3 — Soluções e composição por Produtos
-- ============================================================

CREATE TABLE solucoes (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    unidade_id BIGINT NOT NULL,

    nome VARCHAR(160) NOT NULL,

    descricao VARCHAR(1000),

    rendimento_quantidade NUMERIC(19,6) NOT NULL,

    rendimento_unidade VARCHAR(30) NOT NULL,

    concentracao VARCHAR(160),

    instrucoes_preparo VARCHAR(4000),

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_solucoes_public_id
        UNIQUE (public_id),

    CONSTRAINT uk_solucoes_unidade_nome
        UNIQUE (unidade_id, nome),

    CONSTRAINT fk_solucoes_unidade
        FOREIGN KEY (unidade_id)
        REFERENCES unidades(id),

    CONSTRAINT ck_solucoes_rendimento_positivo
        CHECK (rendimento_quantidade > 0)
);

CREATE INDEX idx_solucoes_unidade
    ON solucoes (unidade_id);

CREATE INDEX idx_solucoes_unidade_ativo
    ON solucoes (unidade_id, ativo);


CREATE TABLE solucao_componentes (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    solucao_id BIGINT NOT NULL,

    produto_id BIGINT NOT NULL,

    ordem INTEGER NOT NULL,

    quantidade NUMERIC(19,6) NOT NULL,

    unidade_medida VARCHAR(30) NOT NULL,

    CONSTRAINT uk_solucao_componentes_public_id
        UNIQUE (public_id),

    CONSTRAINT uk_solucao_componente_produto
        UNIQUE (solucao_id, produto_id),

    CONSTRAINT fk_solucao_componentes_solucao
        FOREIGN KEY (solucao_id)
        REFERENCES solucoes(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_solucao_componentes_produto
        FOREIGN KEY (produto_id)
        REFERENCES produtos(id),

    CONSTRAINT ck_solucao_componentes_ordem
        CHECK (ordem >= 0),

    CONSTRAINT ck_solucao_componentes_quantidade
        CHECK (quantidade > 0)
);

CREATE INDEX idx_solucao_componentes_solucao
    ON solucao_componentes (solucao_id);

CREATE INDEX idx_solucao_componentes_produto
    ON solucao_componentes (produto_id);
