ALTER TABLE produtos
    ALTER COLUMN perecivel SET DEFAULT FALSE,
    ALTER COLUMN ativo SET DEFAULT TRUE;

ALTER TABLE laboratorios
    ALTER COLUMN ativo SET DEFAULT TRUE;

ALTER TABLE usuarios
    ALTER COLUMN ativo SET DEFAULT TRUE;

ALTER TABLE estoque_central
    ALTER COLUMN ativo SET DEFAULT TRUE;

ALTER TABLE lote
    ALTER COLUMN ativo SET DEFAULT TRUE;

ALTER TABLE projetos
    ALTER COLUMN ativo SET DEFAULT TRUE;

ALTER TABLE historico_laboratorio
    ALTER COLUMN ativo SET DEFAULT TRUE;
